global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration (optional - uncomment when alertmanager is configured)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load alert rules
rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'apfa'
    static_configs:
      - targets: ['apfa:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']